import { db } from '@/db';
import { activities } from '@/db/schema';

async function main() {
    const now = new Date();
    const getDateDaysAgo = (days: number) => {
        const date = new Date(now);
        date.setDate(date.getDate() - days);
        return date.toISOString();
    };

    const sampleActivities = [
        // LEAD ACTIVITIES - Created (5)
        {
            leadId: 1,
            userId: 1,
            action: 'created',
            entityType: 'lead',
            entityId: 1,
            entityName: 'John Smith',
            description: 'Lead created by John Smith',
            metadata: JSON.stringify({ source: 'organic', status: 'new lead' }),
            userName: 'John Smith',
            userEmail: 'john.smith@realestate.com',
            createdAt: getDateDaysAgo(28),
        },
        {
            leadId: 5,
            userId: 2,
            action: 'created',
            entityType: 'lead',
            entityId: 5,
            entityName: 'Emily Davis',
            description: 'Lead created by Sarah Johnson',
            metadata: JSON.stringify({ source: 'paid', status: 'new lead' }),
            userName: 'Sarah Johnson',
            userEmail: 'sarah.johnson@realestate.com',
            createdAt: getDateDaysAgo(25),
        },
        {
            leadId: 12,
            userId: 3,
            action: 'created',
            entityType: 'lead',
            entityId: 12,
            entityName: 'Robert Wilson',
            description: 'Lead created by Michael Chen',
            metadata: JSON.stringify({ source: 'referral', status: 'hot lead' }),
            userName: 'Michael Chen',
            userEmail: 'michael.chen@realestate.com',
            createdAt: getDateDaysAgo(20),
        },
        {
            leadId: 18,
            userId: 4,
            action: 'created',
            entityType: 'lead',
            entityId: 18,
            entityName: 'Lisa Anderson',
            description: 'Lead created by Emma Williams',
            metadata: JSON.stringify({ source: 'walk-in', status: 'new lead' }),
            userName: 'Emma Williams',
            userEmail: 'emma.williams@realestate.com',
            createdAt: getDateDaysAgo(15),
        },
        {
            leadId: 25,
            userId: 5,
            action: 'created',
            entityType: 'lead',
            entityId: 25,
            entityName: 'David Martinez',
            description: 'Lead created by James Brown',
            metadata: JSON.stringify({ source: 'organic', status: 'new lead' }),
            userName: 'James Brown',
            userEmail: 'james.brown@realestate.com',
            createdAt: getDateDaysAgo(10),
        },

        // LEAD ACTIVITIES - Updated (8)
        {
            leadId: 1,
            userId: 1,
            action: 'updated',
            entityType: 'lead',
            entityId: 1,
            entityName: 'John Smith',
            description: 'Lead budget updated from $500k-$750k to $750k-$1M',
            metadata: JSON.stringify({ field: 'budget', oldValue: '$500k-$750k', newValue: '$750k-$1M' }),
            userName: 'John Smith',
            userEmail: 'john.smith@realestate.com',
            createdAt: getDateDaysAgo(27),
        },
        {
            leadId: 5,
            userId: 2,
            action: 'updated',
            entityType: 'lead',
            entityId: 5,
            entityName: 'Emily Davis',
            description: 'Lead phone number updated',
            metadata: JSON.stringify({ field: 'phone', oldValue: '+1-555-0100', newValue: '+1-555-0199' }),
            userName: 'Sarah Johnson',
            userEmail: 'sarah.johnson@realestate.com',
            createdAt: getDateDaysAgo(24),
        },
        {
            leadId: 8,
            userId: 3,
            action: 'updated',
            entityType: 'lead',
            entityId: 8,
            entityName: 'Chris Taylor',
            description: 'Lead assigned to broker',
            metadata: JSON.stringify({ field: 'brokerId', oldValue: null, newValue: 2 }),
            userName: 'Michael Chen',
            userEmail: 'michael.chen@realestate.com',
            createdAt: getDateDaysAgo(22),
        },
        {
            leadId: 12,
            userId: 4,
            action: 'updated',
            entityType: 'lead',
            entityId: 12,
            entityName: 'Robert Wilson',
            description: 'Lead score increased from 45 to 75',
            metadata: JSON.stringify({ field: 'score', oldValue: 45, newValue: 75 }),
            userName: 'Emma Williams',
            userEmail: 'emma.williams@realestate.com',
            createdAt: getDateDaysAgo(19),
        },
        {
            leadId: 15,
            userId: 5,
            action: 'updated',
            entityType: 'lead',
            entityId: 15,
            entityName: 'Jennifer Lee',
            description: 'Lead project interest updated',
            metadata: JSON.stringify({ field: 'projectId', oldValue: 3, newValue: 7 }),
            userName: 'James Brown',
            userEmail: 'james.brown@realestate.com',
            createdAt: getDateDaysAgo(16),
        },
        {
            leadId: 18,
            userId: 6,
            action: 'updated',
            entityType: 'lead',
            entityId: 18,
            entityName: 'Lisa Anderson',
            description: 'Lead tags updated',
            metadata: JSON.stringify({ field: 'tags', oldValue: ['urgent'], newValue: ['urgent', 'high-value'] }),
            userName: 'Olivia Garcia',
            userEmail: 'olivia.garcia@realestate.com',
            createdAt: getDateDaysAgo(14),
        },
        {
            leadId: 22,
            userId: 7,
            action: 'updated',
            entityType: 'lead',
            entityId: 22,
            entityName: 'Thomas Moore',
            description: 'Next call date scheduled',
            metadata: JSON.stringify({ field: 'nextCallDate', oldValue: null, newValue: '2024-03-15' }),
            userName: 'Daniel Martinez',
            userEmail: 'daniel.martinez@realestate.com',
            createdAt: getDateDaysAgo(12),
        },
        {
            leadId: 25,
            userId: 8,
            action: 'updated',
            entityType: 'lead',
            entityId: 25,
            entityName: 'David Martinez',
            description: 'Lead interested in property type updated',
            metadata: JSON.stringify({ field: 'interestedIn', oldValue: 'apartment', newValue: 'villa' }),
            userName: 'Sophia Rodriguez',
            userEmail: 'sophia.rodriguez@realestate.com',
            createdAt: getDateDaysAgo(9),
        },

        // LEAD ACTIVITIES - Stage Changed (5)
        {
            leadId: 1,
            userId: 1,
            action: 'stage-changed',
            entityType: 'lead',
            entityId: 1,
            entityName: 'John Smith',
            description: 'Lead stage changed from new to contacted',
            metadata: JSON.stringify({ from: 'new', to: 'contacted' }),
            userName: 'John Smith',
            userEmail: 'john.smith@realestate.com',
            createdAt: getDateDaysAgo(26),
        },
        {
            leadId: 5,
            userId: 2,
            action: 'stage-changed',
            entityType: 'lead',
            entityId: 5,
            entityName: 'Emily Davis',
            description: 'Lead stage changed from contacted to qualified',
            metadata: JSON.stringify({ from: 'contacted', to: 'qualified' }),
            userName: 'Sarah Johnson',
            userEmail: 'sarah.johnson@realestate.com',
            createdAt: getDateDaysAgo(23),
        },
        {
            leadId: 12,
            userId: 3,
            action: 'stage-changed',
            entityType: 'lead',
            entityId: 12,
            entityName: 'Robert Wilson',
            description: 'Lead stage changed from qualified to negotiation',
            metadata: JSON.stringify({ from: 'qualified', to: 'negotiation' }),
            userName: 'Michael Chen',
            userEmail: 'michael.chen@realestate.com',
            createdAt: getDateDaysAgo(18),
        },
        {
            leadId: 18,
            userId: 4,
            action: 'stage-changed',
            entityType: 'lead',
            entityId: 18,
            entityName: 'Lisa Anderson',
            description: 'Lead stage changed from new to contacted',
            metadata: JSON.stringify({ from: 'new', to: 'contacted' }),
            userName: 'Emma Williams',
            userEmail: 'emma.williams@realestate.com',
            createdAt: getDateDaysAgo(13),
        },
        {
            leadId: 12,
            userId: 3,
            action: 'stage-changed',
            entityType: 'lead',
            entityId: 12,
            entityName: 'Robert Wilson',
            description: 'Lead stage changed from negotiation to closed won',
            metadata: JSON.stringify({ from: 'negotiation', to: 'closed won' }),
            userName: 'Michael Chen',
            userEmail: 'michael.chen@realestate.com',
            createdAt: getDateDaysAgo(8),
        },

        // LEAD ACTIVITIES - Deleted (2)
        {
            leadId: null,
            userId: 9,
            action: 'deleted',
            entityType: 'lead',
            entityId: 48,
            entityName: 'Mark Thompson',
            description: 'Lead deleted - marked as duplicate',
            metadata: JSON.stringify({ reason: 'duplicate', duplicateOf: 12 }),
            userName: 'William Taylor',
            userEmail: 'william.taylor@realestate.com',
            createdAt: getDateDaysAgo(11),
        },
        {
            leadId: null,
            userId: 10,
            action: 'deleted',
            entityType: 'lead',
            entityId: 52,
            entityName: 'Susan White',
            description: 'Lead deleted - no longer interested',
            metadata: JSON.stringify({ reason: 'not_interested' }),
            userName: 'Ava Anderson',
            userEmail: 'ava.anderson@realestate.com',
            createdAt: getDateDaysAgo(6),
        },

        // COMMENT ACTIVITIES - Description Added (10)
        {
            leadId: 1,
            userId: 1,
            action: 'description-added',
            entityType: 'comment',
            entityId: 1,
            entityName: 'Initial Contact',
            description: 'Comment added to lead - Initial phone contact made',
            metadata: JSON.stringify({ commentLength: 85 }),
            userName: 'John Smith',
            userEmail: 'john.smith@realestate.com',
            createdAt: getDateDaysAgo(26),
        },
        {
            leadId: 5,
            userId: 2,
            action: 'description-added',
            entityType: 'comment',
            entityId: 2,
            entityName: 'Follow-up Meeting',
            description: 'Comment added to lead - Scheduled site visit for next week',
            metadata: JSON.stringify({ commentLength: 120 }),
            userName: 'Sarah Johnson',
            userEmail: 'sarah.johnson@realestate.com',
            createdAt: getDateDaysAgo(23),
        },
        {
            leadId: 8,
            userId: 3,
            action: 'description-added',
            entityType: 'comment',
            entityId: 3,
            entityName: 'Budget Discussion',
            description: 'Comment added to lead - Client confirmed budget range',
            metadata: JSON.stringify({ commentLength: 95 }),
            userName: 'Michael Chen',
            userEmail: 'michael.chen@realestate.com',
            createdAt: getDateDaysAgo(21),
        },
        {
            leadId: 12,
            userId: 4,
            action: 'description-added',
            entityType: 'comment',
            entityId: 4,
            entityName: 'Property Interest',
            description: 'Comment added to lead - Very interested in Skyline Towers',
            metadata: JSON.stringify({ commentLength: 110 }),
            userName: 'Emma Williams',
            userEmail: 'emma.williams@realestate.com',
            createdAt: getDateDaysAgo(18),
        },
        {
            leadId: 15,
            userId: 5,
            action: 'description-added',
            entityType: 'comment',
            entityId: 5,
            entityName: 'Negotiation Update',
            description: 'Comment added to lead - Price negotiation in progress',
            metadata: JSON.stringify({ commentLength: 140 }),
            userName: 'James Brown',
            userEmail: 'james.brown@realestate.com',
            createdAt: getDateDaysAgo(16),
        },
        {
            leadId: 18,
            userId: 6,
            action: 'description-added',
            entityType: 'comment',
            entityId: 6,
            entityName: 'Site Visit Feedback',
            description: 'Comment added to lead - Client loved the property amenities',
            metadata: JSON.stringify({ commentLength: 165 }),
            userName: 'Olivia Garcia',
            userEmail: 'olivia.garcia@realestate.com',
            createdAt: getDateDaysAgo(13),
        },
        {
            leadId: 22,
            userId: 7,
            action: 'description-added',
            entityType: 'comment',
            entityId: 7,
            entityName: 'Document Request',
            description: 'Comment added to lead - Requested financial documents',
            metadata: JSON.stringify({ commentLength: 88 }),
            userName: 'Daniel Martinez',
            userEmail: 'daniel.martinez@realestate.com',
            createdAt: getDateDaysAgo(11),
        },
        {
            leadId: 25,
            userId: 8,
            action: 'description-added',
            entityType: 'comment',
            entityId: 8,
            entityName: 'Broker Meeting',
            description: 'Comment added to lead - Met with broker to discuss terms',
            metadata: JSON.stringify({ commentLength: 130 }),
            userName: 'Sophia Rodriguez',
            userEmail: 'sophia.rodriguez@realestate.com',
            createdAt: getDateDaysAgo(9),
        },
        {
            leadId: 28,
            userId: 9,
            action: 'description-added',
            entityType: 'comment',
            entityId: 9,
            entityName: 'Payment Discussion',
            description: 'Comment added to lead - Discussing payment plan options',
            metadata: JSON.stringify({ commentLength: 105 }),
            userName: 'William Taylor',
            userEmail: 'william.taylor@realestate.com',
            createdAt: getDateDaysAgo(7),
        },
        {
            leadId: 30,
            userId: 10,
            action: 'description-added',
            entityType: 'comment',
            entityId: 10,
            entityName: 'Contract Ready',
            description: 'Comment added to lead - Contract prepared and ready for signature',
            metadata: JSON.stringify({ commentLength: 92 }),
            userName: 'Ava Anderson',
            userEmail: 'ava.anderson@realestate.com',
            createdAt: getDateDaysAgo(4),
        },

        // COMMENT ACTIVITIES - Description Updated (3)
        {
            leadId: 1,
            userId: 1,
            action: 'description-updated',
            entityType: 'comment',
            entityId: 1,
            entityName: 'Initial Contact',
            description: 'Comment updated on lead - Added phone call outcome details',
            metadata: JSON.stringify({ oldLength: 85, newLength: 145 }),
            userName: 'John Smith',
            userEmail: 'john.smith@realestate.com',
            createdAt: getDateDaysAgo(25),
        },
        {
            leadId: 12,
            userId: 4,
            action: 'description-updated',
            entityType: 'comment',
            entityId: 4,
            entityName: 'Property Interest',
            description: 'Comment updated on lead - Clarified unit preferences',
            metadata: JSON.stringify({ oldLength: 110, newLength: 175 }),
            userName: 'Emma Williams',
            userEmail: 'emma.williams@realestate.com',
            createdAt: getDateDaysAgo(17),
        },
        {
            leadId: 25,
            userId: 8,
            action: 'description-updated',
            entityType: 'comment',
            entityId: 8,
            entityName: 'Broker Meeting',
            description: 'Comment updated on lead - Added broker commission details',
            metadata: JSON.stringify({ oldLength: 130, newLength: 210 }),
            userName: 'Sophia Rodriguez',
            userEmail: 'sophia.rodriguez@realestate.com',
            createdAt: getDateDaysAgo(8),
        },

        // COMMENT ACTIVITIES - Description Deleted (2)
        {
            leadId: 8,
            userId: 3,
            action: 'description-deleted',
            entityType: 'comment',
            entityId: 11,
            entityName: 'Outdated Note',
            description: 'Comment deleted from lead - Information no longer relevant',
            metadata: JSON.stringify({ reason: 'outdated' }),
            userName: 'Michael Chen',
            userEmail: 'michael.chen@realestate.com',
            createdAt: getDateDaysAgo(10),
        },
        {
            leadId: 22,
            userId: 7,
            action: 'description-deleted',
            entityType: 'comment',
            entityId: 12,
            entityName: 'Duplicate Entry',
            description: 'Comment deleted from lead - Duplicate information removed',
            metadata: JSON.stringify({ reason: 'duplicate' }),
            userName: 'Daniel Martinez',
            userEmail: 'daniel.martinez@realestate.com',
            createdAt: getDateDaysAgo(5),
        },

        // PROJECT ACTIVITIES - Created (3)
        {
            leadId: null,
            userId: 1,
            action: 'created',
            entityType: 'project',
            entityId: 1,
            entityName: 'Skyline Towers',
            description: 'Project created by John Smith',
            metadata: JSON.stringify({ type: 'residential', status: 'under-construction' }),
            userName: 'John Smith',
            userEmail: 'john.smith@realestate.com',
            createdAt: getDateDaysAgo(29),
        },
        {
            leadId: null,
            userId: 2,
            action: 'created',
            entityType: 'project',
            entityId: 8,
            entityName: 'Marina Bay Complex',
            description: 'Project created by Sarah Johnson',
            metadata: JSON.stringify({ type: 'commercial', status: 'planning' }),
            userName: 'Sarah Johnson',
            userEmail: 'sarah.johnson@realestate.com',
            createdAt: getDateDaysAgo(24),
        },
        {
            leadId: null,
            userId: 3,
            action: 'created',
            entityType: 'project',
            entityId: 14,
            entityName: 'Green Valley Estates',
            description: 'Project created by Michael Chen',
            metadata: JSON.stringify({ type: 'residential', status: 'planning' }),
            userName: 'Michael Chen',
            userEmail: 'michael.chen@realestate.com',
            createdAt: getDateDaysAgo(15),
        },

        // PROJECT ACTIVITIES - Updated (5)
        {
            leadId: null,
            userId: 1,
            action: 'updated',
            entityType: 'project',
            entityId: 1,
            entityName: 'Skyline Towers',
            description: 'Project status updated from planning to under-construction',
            metadata: JSON.stringify({ field: 'status', oldValue: 'planning', newValue: 'under-construction' }),
            userName: 'John Smith',
            userEmail: 'john.smith@realestate.com',
            createdAt: getDateDaysAgo(27),
        },
        {
            leadId: null,
            userId: 2,
            action: 'updated',
            entityType: 'project',
            entityId: 3,
            entityName: 'Palm Beach Residences',
            description: 'Project price updated',
            metadata: JSON.stringify({ field: 'price', oldValue: '$800k-$1.2M', newValue: '$850k-$1.3M' }),
            userName: 'Sarah Johnson',
            userEmail: 'sarah.johnson@realestate.com',
            createdAt: getDateDaysAgo(22),
        },
        {
            leadId: null,
            userId: 4,
            action: 'updated',
            entityType: 'project',
            entityId: 5,
            entityName: 'Downtown Square',
            description: 'Project amenities updated',
            metadata: JSON.stringify({ field: 'amenities', added: ['rooftop garden', 'co-working space'] }),
            userName: 'Emma Williams',
            userEmail: 'emma.williams@realestate.com',
            createdAt: getDateDaysAgo(19),
        },
        {
            leadId: null,
            userId: 5,
            action: 'updated',
            entityType: 'project',
            entityId: 8,
            entityName: 'Marina Bay Complex',
            description: 'Project images added',
            metadata: JSON.stringify({ field: 'images', count: 12 }),
            userName: 'James Brown',
            userEmail: 'james.brown@realestate.com',
            createdAt: getDateDaysAgo(14),
        },
        {
            leadId: null,
            userId: 6,
            action: 'updated',
            entityType: 'project',
            entityId: 10,
            entityName: 'Riverside Gardens',
            description: 'Project units information updated',
            metadata: JSON.stringify({ field: 'units', totalUnits: 85, available: 62 }),
            userName: 'Olivia Garcia',
            userEmail: 'olivia.garcia@realestate.com',
            createdAt: getDateDaysAgo(12),
        },

        // PROJECT ACTIVITIES - Deleted (2)
        {
            leadId: null,
            userId: 7,
            action: 'deleted',
            entityType: 'project',
            entityId: 16,
            entityName: 'Sunset Villas',
            description: 'Project deleted - Development cancelled',
            metadata: JSON.stringify({ reason: 'cancelled', status: 'planning' }),
            userName: 'Daniel Martinez',
            userEmail: 'daniel.martinez@realestate.com',
            createdAt: getDateDaysAgo(10),
        },
        {
            leadId: null,
            userId: 8,
            action: 'deleted',
            entityType: 'project',
            entityId: 18,
            entityName: 'Mountain View Heights',
            description: 'Project deleted - Merged with another project',
            metadata: JSON.stringify({ reason: 'merged', mergedInto: 14 }),
            userName: 'Sophia Rodriguez',
            userEmail: 'sophia.rodriguez@realestate.com',
            createdAt: getDateDaysAgo(6),
        },

        // PIPELINE ACTIVITIES - Created (2)
        {
            leadId: null,
            userId: 1,
            action: 'created',
            entityType: 'pipeline',
            entityId: 1,
            entityName: 'Q1 2024 Sales Pipeline',
            description: 'Pipeline created by John Smith',
            metadata: JSON.stringify({ stages: ['new', 'contacted', 'qualified', 'negotiation', 'closed'] }),
            userName: 'John Smith',
            userEmail: 'john.smith@realestate.com',
            createdAt: getDateDaysAgo(30),
        },
        {
            leadId: null,
            userId: 2,
            action: 'created',
            entityType: 'pipeline',
            entityId: 2,
            entityName: 'Premium Properties Pipeline',
            description: 'Pipeline created by Sarah Johnson',
            metadata: JSON.stringify({ stages: ['prospect', 'viewing', 'offer', 'closing'] }),
            userName: 'Sarah Johnson',
            userEmail: 'sarah.johnson@realestate.com',
            createdAt: getDateDaysAgo(25),
        },

        // PIPELINE ACTIVITIES - Updated (2)
        {
            leadId: null,
            userId: 1,
            action: 'updated',
            entityType: 'pipeline',
            entityId: 1,
            entityName: 'Q1 2024 Sales Pipeline',
            description: 'Pipeline stages reordered',
            metadata: JSON.stringify({ field: 'stages', action: 'reordered' }),
            userName: 'John Smith',
            userEmail: 'john.smith@realestate.com',
            createdAt: getDateDaysAgo(20),
        },
        {
            leadId: null,
            userId: 3,
            action: 'updated',
            entityType: 'pipeline',
            entityId: 2,
            entityName: 'Premium Properties Pipeline',
            description: 'Pipeline settings updated',
            metadata: JSON.stringify({ field: 'settings', updated: ['automation', 'notifications'] }),
            userName: 'Michael Chen',
            userEmail: 'michael.chen@realestate.com',
            createdAt: getDateDaysAgo(15),
        },

        // PIPELINE ACTIVITIES - Deleted (1)
        {
            leadId: null,
            userId: 4,
            action: 'deleted',
            entityType: 'pipeline',
            entityId: 3,
            entityName: 'Old Sales Process',
            description: 'Pipeline deleted - Replaced with new workflow',
            metadata: JSON.stringify({ reason: 'obsolete', replacedBy: 1 }),
            userName: 'Emma Williams',
            userEmail: 'emma.williams@realestate.com',
            createdAt: getDateDaysAgo(18),
        },
    ];

    await db.insert(activities).values(sampleActivities);
    
    console.log('✅ Activities seeder completed successfully - 50 audit log entries created');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});