import { db } from '@/db';
import { brokers } from '@/db/schema';

async function main() {
    const sampleBrokers = [
        {
            name: 'Robert Williams',
            company: 'Century Properties',
            email: 'robert.williams@centuryproperties.com',
            phone: '+1-555-234-5678',
            commission: '2.5%',
            totalDeals: 35,
            totalRevenue: '7500000',
            isActive: true,
            joinedAt: new Date('2021-03-15').toISOString(),
        },
        {
            name: 'Jennifer Martinez',
            company: 'Prime Realty',
            email: 'jennifer.martinez@primerealty.com',
            phone: '+1-555-345-6789',
            commission: '3%',
            totalDeals: 42,
            totalRevenue: '9200000',
            isActive: true,
            joinedAt: new Date('2020-08-22').toISOString(),
        },
        {
            name: 'Michael Thompson',
            company: 'Independent Broker',
            email: 'michael.thompson@gmail.com',
            phone: '+1-555-456-7890',
            commission: '4%',
            totalDeals: 28,
            totalRevenue: '6800000',
            isActive: true,
            joinedAt: new Date('2021-11-10').toISOString(),
        },
        {
            name: 'Lisa Davis',
            company: 'Metro Brokers',
            email: 'lisa.davis@metrobrokers.com',
            phone: '+1-555-567-8901',
            commission: '2%',
            totalDeals: 18,
            totalRevenue: '3200000',
            isActive: true,
            joinedAt: new Date('2022-06-05').toISOString(),
        },
        {
            name: 'James Anderson',
            company: 'Elite Real Estate',
            email: 'james.anderson@eliterealestate.com',
            phone: '+1-555-678-9012',
            commission: '2.5%',
            totalDeals: 22,
            totalRevenue: '4100000',
            isActive: true,
            joinedAt: new Date('2022-09-18').toISOString(),
        },
        {
            name: 'Patricia Moore',
            company: 'First Choice Brokers',
            email: 'patricia.moore@firstchoice.com',
            phone: '+1-555-789-0123',
            commission: '3%',
            totalDeals: 15,
            totalRevenue: '2800000',
            isActive: true,
            joinedAt: new Date('2023-01-12').toISOString(),
        },
        {
            name: 'David Jackson',
            company: 'Self Employed',
            email: 'david.jackson@outlook.com',
            phone: '+1-555-890-1234',
            commission: '3.5%',
            totalDeals: 12,
            totalRevenue: '2100000',
            isActive: false,
            joinedAt: new Date('2023-03-25').toISOString(),
        },
        {
            name: 'Sarah White',
            company: 'Century Properties',
            email: 'sarah.white@centuryproperties.com',
            phone: '+1-555-901-2345',
            commission: '2%',
            totalDeals: 10,
            totalRevenue: '1600000',
            isActive: true,
            joinedAt: new Date('2023-07-08').toISOString(),
        },
        {
            name: 'Christopher Harris',
            company: 'Prime Realty',
            email: 'christopher.harris@primerealty.com',
            phone: '+1-555-012-3456',
            commission: '2.5%',
            totalDeals: 6,
            totalRevenue: '850000',
            isActive: true,
            joinedAt: new Date('2023-10-14').toISOString(),
        },
        {
            name: 'Nancy Clark',
            company: 'Independent Broker',
            email: 'nancy.clark@yahoo.com',
            phone: '+1-555-123-4567',
            commission: '1.5%',
            totalDeals: 3,
            totalRevenue: '420000',
            isActive: true,
            joinedAt: new Date('2024-02-20').toISOString(),
        },
        {
            name: 'Daniel Lewis',
            company: 'Metro Brokers',
            email: 'daniel.lewis@metrobrokers.com',
            phone: '+1-555-234-5679',
            commission: '2%',
            totalDeals: 8,
            totalRevenue: '1200000',
            isActive: true,
            joinedAt: new Date('2023-11-30').toISOString(),
        },
        {
            name: 'Karen Walker',
            company: 'Elite Real Estate',
            email: 'karen.walker@eliterealestate.com',
            phone: '+1-555-345-6780',
            commission: '2.5%',
            totalDeals: 1,
            totalRevenue: '180000',
            isActive: false,
            joinedAt: new Date('2024-05-10').toISOString(),
        },
    ];

    await db.insert(brokers).values(sampleBrokers);
    
    console.log('✅ Brokers seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});