import { db } from '@/db';
import { leads } from '@/db/schema';

async function main() {
    const sampleLeads = [
        {
            firstName: 'Priya',
            lastName: 'Sharma',
            email: 'priya.sharma@gmail.com',
            phone: '+1-555-234-5678',
            source: 'organic',
            subSource: null,
            status: 'new lead',
            stage: 'new',
            budget: '$250k-$500k',
            interestedIn: '3BHK Apartment',
            projectId: null,
            assignedTo: null,
            score: 55,
            tags: JSON.stringify(['first-time-buyer']),
            notes: null,
            lastContactedAt: null,
            nextCallDate: null,
            createdAt: new Date('2024-12-15').toISOString(),
            updatedAt: new Date('2024-12-15').toISOString(),
        },
        {
            firstName: 'Michael',
            lastName: 'Johnson',
            email: 'michael.j@outlook.com',
            phone: '+1-555-876-5432',
            source: 'paid',
            subSource: 'Google Ads',
            status: 'hot lead',
            stage: 'site visited',
            budget: '$500k-$1M',
            interestedIn: '4BHK Villa',
            projectId: 7,
            assignedTo: 3,
            score: 88,
            tags: JSON.stringify(['urgent', 'pre-approved']),
            notes: 'Pre-approved for $650k loan. Very interested in north-facing units.',
            lastContactedAt: new Date('2024-12-22').toISOString(),
            nextCallDate: new Date('2024-12-28').toISOString(),
            createdAt: new Date('2024-11-20').toISOString(),
            updatedAt: new Date('2024-12-22').toISOString(),
        },
        {
            firstName: 'Emily',
            lastName: 'Rodriguez',
            email: 'emily.rodriguez@yahoo.com',
            phone: '+1-555-345-6789',
            source: 'referral',
            subSource: 'Broker Network',
            status: 'booked lead',
            stage: 'attempted 2',
            budget: '$250k-$500k',
            interestedIn: '3BHK Apartment',
            projectId: 3,
            assignedTo: 5,
            score: 78,
            tags: JSON.stringify(['referral-bonus', 'relocating']),
            notes: 'Referred by John Doe. Looking for immediate possession.',
            lastContactedAt: new Date('2024-12-20').toISOString(),
            nextCallDate: new Date('2024-12-27').toISOString(),
            createdAt: new Date('2024-11-28').toISOString(),
            updatedAt: new Date('2024-12-20').toISOString(),
        },
        {
            firstName: 'Rahul',
            lastName: 'Patel',
            email: 'rahul.patel@gmail.com',
            phone: '+1-555-567-8901',
            source: 'organic',
            subSource: null,
            status: 'dead lead',
            stage: 'unqualified',
            budget: '$50k-$100k',
            interestedIn: 'Studio Apartment',
            projectId: null,
            assignedTo: 2,
            score: 22,
            tags: JSON.stringify([]),
            notes: 'Budget too low for available properties.',
            lastContactedAt: new Date('2024-11-10').toISOString(),
            nextCallDate: null,
            createdAt: new Date('2024-10-15').toISOString(),
            updatedAt: new Date('2024-11-10').toISOString(),
        },
        {
            firstName: 'Chen',
            lastName: 'Wei',
            email: 'chen.wei@hotmail.com',
            phone: '+1-555-789-0123',
            source: 'paid',
            subSource: 'Facebook',
            status: 'hot lead',
            stage: 'attempted 1',
            budget: '$1M+',
            interestedIn: 'Penthouse',
            projectId: 12,
            assignedTo: 1,
            score: 92,
            tags: JSON.stringify(['high-value', 'investor', 'cash-buyer']),
            notes: 'Cash buyer. Looking for luxury penthouse with city view.',
            lastContactedAt: new Date('2024-12-23').toISOString(),
            nextCallDate: new Date('2024-12-26').toISOString(),
            createdAt: new Date('2024-12-10').toISOString(),
            updatedAt: new Date('2024-12-23').toISOString(),
        },
        {
            firstName: 'Sarah',
            lastName: 'Williams',
            email: 'sarah.williams@gmail.com',
            phone: '+1-555-234-9876',
            source: 'walk-in',
            subSource: null,
            status: 'new lead',
            stage: 'new',
            budget: '$100k-$250k',
            interestedIn: '2BHK Apartment',
            projectId: null,
            assignedTo: null,
            score: 45,
            tags: JSON.stringify(['first-time-buyer']),
            notes: null,
            lastContactedAt: null,
            nextCallDate: null,
            createdAt: new Date('2024-12-24').toISOString(),
            updatedAt: new Date('2024-12-24').toISOString(),
        },
        {
            firstName: 'Amit',
            lastName: 'Singh',
            email: 'amit.singh@yahoo.com',
            phone: '+1-555-456-7890',
            source: 'organic',
            subSource: null,
            status: 'booked lead',
            stage: 'site visited',
            budget: '$500k-$1M',
            interestedIn: '4BHK Villa',
            projectId: 9,
            assignedTo: 7,
            score: 82,
            tags: JSON.stringify(['urgent', 'relocating']),
            notes: 'Wants parking for 2 cars. Visited site last week.',
            lastContactedAt: new Date('2024-12-21').toISOString(),
            nextCallDate: new Date('2024-12-29').toISOString(),
            createdAt: new Date('2024-11-15').toISOString(),
            updatedAt: new Date('2024-12-21').toISOString(),
        },
        {
            firstName: 'Jessica',
            lastName: 'Brown',
            email: 'jessica.brown@outlook.com',
            phone: '+1-555-678-9012',
            source: 'paid',
            subSource: 'Instagram',
            status: 'new lead',
            stage: 'attempted 1',
            budget: '$250k-$500k',
            interestedIn: '3BHK Apartment',
            projectId: 5,
            assignedTo: 4,
            score: 58,
            tags: JSON.stringify(['first-time-buyer']),
            notes: 'Interested in north-facing units.',
            lastContactedAt: new Date('2024-12-22').toISOString(),
            nextCallDate: new Date('2024-12-30').toISOString(),
            createdAt: new Date('2024-12-05').toISOString(),
            updatedAt: new Date('2024-12-22').toISOString(),
        },
        {
            firstName: 'Vikram',
            lastName: 'Reddy',
            email: 'vikram.reddy@gmail.com',
            phone: '+1-555-890-1234',
            source: 'referral',
            subSource: 'Broker Network',
            status: 'hot lead',
            stage: 'closed won',
            budget: '$250k-$500k',
            interestedIn: '3BHK Apartment',
            projectId: 4,
            assignedTo: 6,
            score: 95,
            tags: JSON.stringify(['referral-bonus']),
            notes: 'Deal closed. Token amount received.',
            lastContactedAt: new Date('2024-12-18').toISOString(),
            nextCallDate: null,
            createdAt: new Date('2024-10-20').toISOString(),
            updatedAt: new Date('2024-12-18').toISOString(),
        },
        {
            firstName: 'Maria',
            lastName: 'Garcia',
            email: 'maria.garcia@hotmail.com',
            phone: '+1-555-012-3456',
            source: 'organic',
            subSource: null,
            status: 'duplicate lead',
            stage: 'new',
            budget: '$100k-$250k',
            interestedIn: '2BHK Apartment',
            projectId: null,
            assignedTo: null,
            score: 15,
            tags: JSON.stringify([]),
            notes: 'Duplicate entry - already exists in system.',
            lastContactedAt: null,
            nextCallDate: null,
            createdAt: new Date('2024-12-23').toISOString(),
            updatedAt: new Date('2024-12-23').toISOString(),
        },
        {
            firstName: 'David',
            lastName: 'Kim',
            email: 'david.kim@gmail.com',
            phone: '+1-555-123-4567',
            source: 'paid',
            subSource: 'Google Ads',
            status: 'new lead',
            stage: 'attempted 2',
            budget: '$500k-$1M',
            interestedIn: 'Duplex',
            projectId: 11,
            assignedTo: 8,
            score: 62,
            tags: JSON.stringify(['investor']),
            notes: 'Looking for investment property.',
            lastContactedAt: new Date('2024-12-19').toISOString(),
            nextCallDate: new Date('2024-12-31').toISOString(),
            createdAt: new Date('2024-11-25').toISOString(),
            updatedAt: new Date('2024-12-19').toISOString(),
        },
        {
            firstName: 'Anjali',
            lastName: 'Gupta',
            email: 'anjali.gupta@yahoo.com',
            phone: '+1-555-234-5670',
            source: 'organic',
            subSource: null,
            status: 'hot lead',
            stage: 'attempted 2',
            budget: '$250k-$500k',
            interestedIn: '3BHK Apartment',
            projectId: 2,
            assignedTo: 9,
            score: 85,
            tags: JSON.stringify(['urgent', 'first-time-buyer']),
            notes: 'Budget flexible if right property found.',
            lastContactedAt: new Date('2024-12-23').toISOString(),
            nextCallDate: new Date('2024-12-28').toISOString(),
            createdAt: new Date('2024-12-01').toISOString(),
            updatedAt: new Date('2024-12-23').toISOString(),
        },
        {
            firstName: 'Robert',
            lastName: 'Taylor',
            email: 'robert.taylor@outlook.com',
            phone: '+1-555-345-6781',
            source: 'walk-in',
            subSource: null,
            status: 'new lead',
            stage: 'new',
            budget: '$1M+',
            interestedIn: 'Commercial Space',
            projectId: null,
            assignedTo: null,
            score: 68,
            tags: JSON.stringify(['high-value', 'investor']),
            notes: null,
            lastContactedAt: null,
            nextCallDate: null,
            createdAt: new Date('2024-12-22').toISOString(),
            updatedAt: new Date('2024-12-22').toISOString(),
        },
        {
            firstName: 'Meera',
            lastName: 'Nair',
            email: 'meera.nair@gmail.com',
            phone: '+1-555-456-7892',
            source: 'referral',
            subSource: 'Broker Network',
            status: 'booked lead',
            stage: 'attempted 1',
            budget: '$100k-$250k',
            interestedIn: '2BHK Apartment',
            projectId: 6,
            assignedTo: 10,
            score: 72,
            tags: JSON.stringify(['referral-bonus']),
            notes: 'Referred by Sarah Williams.',
            lastContactedAt: new Date('2024-12-24').toISOString(),
            nextCallDate: new Date('2024-12-27').toISOString(),
            createdAt: new Date('2024-12-08').toISOString(),
            updatedAt: new Date('2024-12-24').toISOString(),
        },
        {
            firstName: 'James',
            lastName: 'Anderson',
            email: 'james.anderson@hotmail.com',
            phone: '+1-555-567-8903',
            source: 'paid',
            subSource: 'Facebook',
            status: 'dead lead',
            stage: 'unqualified',
            budget: '$50k-$100k',
            interestedIn: '1BHK Apartment',
            projectId: null,
            assignedTo: 3,
            score: 18,
            tags: JSON.stringify([]),
            notes: 'Not responding to calls.',
            lastContactedAt: new Date('2024-11-05').toISOString(),
            nextCallDate: null,
            createdAt: new Date('2024-10-10').toISOString(),
            updatedAt: new Date('2024-11-05').toISOString(),
        },
        {
            firstName: 'Sneha',
            lastName: 'Kapoor',
            email: 'sneha.kapoor@gmail.com',
            phone: '+1-555-678-9014',
            source: 'organic',
            subSource: null,
            status: 'new lead',
            stage: 'new',
            budget: '$250k-$500k',
            interestedIn: '3BHK Apartment',
            projectId: null,
            assignedTo: null,
            score: 52,
            tags: JSON.stringify([]),
            notes: null,
            lastContactedAt: null,
            nextCallDate: null,
            createdAt: new Date('2024-12-20').toISOString(),
            updatedAt: new Date('2024-12-20').toISOString(),
        },
        {
            firstName: 'Thomas',
            lastName: 'Martinez',
            email: 'thomas.martinez@yahoo.com',
            phone: '+1-555-789-0125',
            source: 'paid',
            subSource: 'Google Ads',
            status: 'hot lead',
            stage: 'site visited',
            budget: '$500k-$1M',
            interestedIn: 'Townhouse',
            projectId: 14,
            assignedTo: 2,
            score: 90,
            tags: JSON.stringify(['urgent', 'cash-buyer']),
            notes: 'Cash buyer. Wants quick closing.',
            lastContactedAt: new Date('2024-12-21').toISOString(),
            nextCallDate: new Date('2024-12-26').toISOString(),
            createdAt: new Date('2024-11-18').toISOString(),
            updatedAt: new Date('2024-12-21').toISOString(),
        },
        {
            firstName: 'Lakshmi',
            lastName: 'Iyer',
            email: 'lakshmi.iyer@outlook.com',
            phone: '+1-555-890-1236',
            source: 'organic',
            subSource: null,
            status: 'booked lead',
            stage: 'attempted 2',
            budget: '$250k-$500k',
            interestedIn: '3BHK Apartment',
            projectId: 8,
            assignedTo: 5,
            score: 75,
            tags: JSON.stringify(['first-time-buyer', 'relocating']),
            notes: 'Relocating from another state. Needs by March.',
            lastContactedAt: new Date('2024-12-22').toISOString(),
            nextCallDate: new Date('2024-12-29').toISOString(),
            createdAt: new Date('2024-11-30').toISOString(),
            updatedAt: new Date('2024-12-22').toISOString(),
        },
        {
            firstName: 'Daniel',
            lastName: 'Wilson',
            email: 'daniel.wilson@gmail.com',
            phone: '+1-555-012-3458',
            source: 'walk-in',
            subSource: null,
            status: 'new lead',
            stage: 'new',
            budget: '$100k-$250k',
            interestedIn: 'Studio Apartment',
            projectId: null,
            assignedTo: null,
            score: 48,
            tags: JSON.stringify([]),
            notes: null,
            lastContactedAt: null,
            nextCallDate: null,
            createdAt: new Date('2024-12-24').toISOString(),
            updatedAt: new Date('2024-12-24').toISOString(),
        },
        {
            firstName: 'Kavya',
            lastName: 'Menon',
            email: 'kavya.menon@hotmail.com',
            phone: '+1-555-123-4569',
            source: 'referral',
            subSource: 'Broker Network',
            status: 'dead lead',
            stage: 'unqualified',
            budget: '$50k-$100k',
            interestedIn: '1BHK Apartment',
            projectId: null,
            assignedTo: 7,
            score: 25,
            tags: JSON.stringify([]),
            notes: 'Changed mind - not interested anymore.',
            lastContactedAt: new Date('2024-11-15').toISOString(),
            nextCallDate: null,
            createdAt: new Date('2024-10-25').toISOString(),
            updatedAt: new Date('2024-11-15').toISOString(),
        },
        {
            firstName: 'Christopher',
            lastName: 'Lee',
            email: 'christopher.lee@gmail.com',
            phone: '+1-555-234-5671',
            source: 'paid',
            subSource: 'Instagram',
            status: 'new lead',
            stage: 'attempted 1',
            budget: '$250k-$500k',
            interestedIn: '2BHK Apartment',
            projectId: 1,
            assignedTo: 4,
            score: 60,
            tags: JSON.stringify(['first-time-buyer']),
            notes: 'Looking for good school district.',
            lastContactedAt: new Date('2024-12-23').toISOString(),
            nextCallDate: new Date('2024-12-30').toISOString(),
            createdAt: new Date('2024-12-12').toISOString(),
            updatedAt: new Date('2024-12-23').toISOString(),
        },
        {
            firstName: 'Divya',
            lastName: 'Krishnan',
            email: 'divya.krishnan@yahoo.com',
            phone: '+1-555-345-6782',
            source: 'organic',
            subSource: null,
            status: 'hot lead',
            stage: 'attempted 1',
            budget: '$500k-$1M',
            interestedIn: '4BHK Apartment',
            projectId: 10,
            assignedTo: 1,
            score: 87,
            tags: JSON.stringify(['urgent', 'pre-approved']),
            notes: 'Pre-approved for $700k loan.',
            lastContactedAt: new Date('2024-12-24').toISOString(),
            nextCallDate: new Date('2024-12-27').toISOString(),
            createdAt: new Date('2024-12-14').toISOString(),
            updatedAt: new Date('2024-12-24').toISOString(),
        },
        {
            firstName: 'Matthew',
            lastName: 'Thomas',
            email: 'matthew.thomas@outlook.com',
            phone: '+1-555-456-7893',
            source: 'organic',
            subSource: null,
            status: 'duplicate lead',
            stage: 'new',
            budget: '$100k-$250k',
            interestedIn: '2BHK Apartment',
            projectId: null,
            assignedTo: null,
            score: 10,
            tags: JSON.stringify([]),
            notes: 'Duplicate - same as lead #4567.',
            lastContactedAt: null,
            nextCallDate: null,
            createdAt: new Date('2024-12-23').toISOString(),
            updatedAt: new Date('2024-12-23').toISOString(),
        },
        {
            firstName: 'Aarti',
            lastName: 'Joshi',
            email: 'aarti.joshi@gmail.com',
            phone: '+1-555-567-8904',
            source: 'paid',
            subSource: 'Facebook',
            status: 'booked lead',
            stage: 'site visited',
            budget: '$250k-$500k',
            interestedIn: '3BHK Apartment',
            projectId: 13,
            assignedTo: 6,
            score: 80,
            tags: JSON.stringify(['urgent', 'relocating']),
            notes: 'Visited site yesterday. Very interested.',
            lastContactedAt: new Date('2024-12-23').toISOString(),
            nextCallDate: new Date('2024-12-28').toISOString(),
            createdAt: new Date('2024-12-02').toISOString(),
            updatedAt: new Date('2024-12-23').toISOString(),
        },
        {
            firstName: 'Andrew',
            lastName: 'White',
            email: 'andrew.white@hotmail.com',
            phone: '+1-555-678-9015',
            source: 'walk-in',
            subSource: null,
            status: 'new lead',
            stage: 'new',
            budget: '$1M+',
            interestedIn: 'Penthouse',
            projectId: null,
            assignedTo: null,
            score: 70,
            tags: JSON.stringify(['high-value']),
            notes: null,
            lastContactedAt: null,
            nextCallDate: null,
            createdAt: new Date('2024-12-24').toISOString(),
            updatedAt: new Date('2024-12-24').toISOString(),
        },
        {
            firstName: 'Deepa',
            lastName: 'Rao',
            email: 'deepa.rao@gmail.com',
            phone: '+1-555-789-0126',
            source: 'referral',
            subSource: 'Broker Network',
            status: 'new lead',
            stage: 'attempted 2',
            budget: '$100k-$250k',
            interestedIn: '2BHK Apartment',
            projectId: 5,
            assignedTo: 9,
            score: 56,
            tags: JSON.stringify(['referral-bonus']),
            notes: 'Referred by Michael Johnson.',
            lastContactedAt: new Date('2024-12-20').toISOString(),
            nextCallDate: new Date('2024-12-30').toISOString(),
            createdAt: new Date('2024-12-07').toISOString(),
            updatedAt: new Date('2024-12-20').toISOString(),
        },
        {
            firstName: 'Joshua',
            lastName: 'Harris',
            email: 'joshua.harris@yahoo.com',
            phone: '+1-555-890-1237',
            source: 'organic',
            subSource: null,
            status: 'dead lead',
            stage: 'unqualified',
            budget: '$50k-$100k',
            interestedIn: 'Studio Apartment',
            projectId: null,
            assignedTo: 3,
            score: 28,
            tags: JSON.stringify([]),
            notes: 'Cannot afford current market prices.',
            lastContactedAt: new Date('2024-11-12').toISOString(),
            nextCallDate: null,
            createdAt: new Date('2024-10-18').toISOString(),
            updatedAt: new Date('2024-11-12').toISOString(),
        },
        {
            firstName: 'Shalini',
            lastName: 'Verma',
            email: 'shalini.verma@outlook.com',
            phone: '+1-555-012-3459',
            source: 'paid',
            subSource: 'Google Ads',
            status: 'hot lead',
            stage: 'attempted 2',
            budget: '$500k-$1M',
            interestedIn: '4BHK Villa',
            projectId: 15,
            assignedTo: 8,
            score: 91,
            tags: JSON.stringify(['urgent', 'investor', 'cash-buyer']),
            notes: 'Cash buyer. Looking for villa with garden.',
            lastContactedAt: new Date('2024-12-22').toISOString(),
            nextCallDate: new Date('2024-12-27').toISOString(),
            createdAt: new Date('2024-11-22').toISOString(),
            updatedAt: new Date('2024-12-22').toISOString(),
        },
        {
            firstName: 'Ryan',
            lastName: 'Clark',
            email: 'ryan.clark@gmail.com',
            phone: '+1-555-123-4560',
            source: 'organic',
            subSource: null,
            status: 'new lead',
            stage: 'new',
            budget: '$250k-$500k',
            interestedIn: '3BHK Apartment',
            projectId: null,
            assignedTo: null,
            score: 50,
            tags: JSON.stringify([]),
            notes: null,
            lastContactedAt: null,
            nextCallDate: null,
            createdAt: new Date('2024-12-21').toISOString(),
            updatedAt: new Date('2024-12-21').toISOString(),
        },
        {
            firstName: 'Neha',
            lastName: 'Desai',
            email: 'neha.desai@hotmail.com',
            phone: '+1-555-234-5672',
            source: 'paid',
            subSource: 'Instagram',
            status: 'booked lead',
            stage: 'attempted 1',
            budget: '$250k-$500k',
            interestedIn: '3BHK Apartment',
            projectId: 7,
            assignedTo: 2,
            score: 76,
            tags: JSON.stringify(['first-time-buyer', 'urgent']),
            notes: 'Looking for immediate possession.',
            lastContactedAt: new Date('2024-12-24').toISOString(),
            nextCallDate: new Date('2024-12-29').toISOString(),
            createdAt: new Date('2024-12-10').toISOString(),
            updatedAt: new Date('2024-12-24').toISOString(),
        },
        {
            firstName: 'Brandon',
            lastName: 'Lewis',
            email: 'brandon.lewis@yahoo.com',
            phone: '+1-555-345-6783',
            source: 'walk-in',
            subSource: null,
            status: 'new lead',
            stage: 'new',
            budget: '$100k-$250k',
            interestedIn: '1BHK Apartment',
            projectId: null,
            assignedTo: null,
            score: 42,
            tags: JSON.stringify([]),
            notes: null,
            lastContactedAt: null,
            nextCallDate: null,
            createdAt: new Date('2024-12-23').toISOString(),
            updatedAt: new Date('2024-12-23').toISOString(),
        },
        {
            firstName: 'Pooja',
            lastName: 'Bhatt',
            email: 'pooja.bhatt@gmail.com',
            phone: '+1-555-456-7894',
            source: 'referral',
            subSource: 'Broker Network',
            status: 'hot lead',
            stage: 'closed won',
            budget: '$250k-$500k',
            interestedIn: '3BHK Apartment',
            projectId: 3,
            assignedTo: 5,
            score: 94,
            tags: JSON.stringify(['referral-bonus']),
            notes: 'Deal finalized. Paperwork in progress.',
            lastContactedAt: new Date('2024-12-20').toISOString(),
            nextCallDate: null,
            createdAt: new Date('2024-10-28').toISOString(),
            updatedAt: new Date('2024-12-20').toISOString(),
        },
        {
            firstName: 'Kevin',
            lastName: 'Robinson',
            email: 'kevin.robinson@outlook.com',
            phone: '+1-555-567-8905',
            source: 'organic',
            subSource: null,
            status: 'duplicate lead',
            stage: 'new',
            budget: '$500k-$1M',
            interestedIn: 'Townhouse',
            projectId: null,
            assignedTo: null,
            score: 12,
            tags: JSON.stringify([]),
            notes: 'Duplicate entry - merge with existing lead.',
            lastContactedAt: null,
            nextCallDate: null,
            createdAt: new Date('2024-12-24').toISOString(),
            updatedAt: new Date('2024-12-24').toISOString(),
        },
        {
            firstName: 'Ritu',
            lastName: 'Saxena',
            email: 'ritu.saxena@hotmail.com',
            phone: '+1-555-678-9016',
            source: 'paid',
            subSource: 'Facebook',
            status: 'new lead',
            stage: 'attempted 1',
            budget: '$100k-$250k',
            interestedIn: '2BHK Apartment',
            projectId: 2,
            assignedTo: 10,
            score: 54,
            tags: JSON.stringify(['first-time-buyer']),
            notes: 'Looking for south-facing units.',
            lastContactedAt: new Date('2024-12-23').toISOString(),
            nextCallDate: new Date('2024-12-31').toISOString(),
            createdAt: new Date('2024-12-13').toISOString(),
            updatedAt: new Date('2024-12-23').toISOString(),
        },
        {
            firstName: 'Justin',
            lastName: 'Walker',
            email: 'justin.walker@gmail.com',
            phone: '+1-555-789-0127',
            source: 'organic',
            subSource: null,
            status: 'dead lead',
            stage: 'unqualified',
            budget: '$50k-$100k',
            interestedIn: 'Studio Apartment',
            projectId: null,
            assignedTo: 4,
            score: 20,
            tags: JSON.stringify([]),
            notes: 'Not ready to buy. Will contact next year.',
            lastContactedAt: new Date('2024-11-08').toISOString(),
            nextCallDate: null,
            createdAt: new Date('2024-10-12').toISOString(),
            updatedAt: new Date('2024-11-08').toISOString(),
        },
        {
            firstName: 'Swati',
            lastName: 'Malhotra',
            email: 'swati.malhotra@yahoo.com',
            phone: '+1-555-890-1238',
            source: 'paid',
            subSource: 'Google Ads',
            status: 'hot lead',
            stage: 'site visited',
            budget: '$500k-$1M',
            interestedIn: 'Duplex',
            projectId: 11,
            assignedTo: 1,
            score: 89,
            tags: JSON.stringify(['urgent', 'pre-approved']),
            notes: 'Pre-approved for $850k. Visited site twice.',
            lastContactedAt: new Date('2024-12-22').toISOString(),
            nextCallDate: new Date('2024-12-26').toISOString(),
            createdAt: new Date('2024-11-27').toISOString(),
            updatedAt: new Date('2024-12-22').toISOString(),
        },
        {
            firstName: 'Eric',
            lastName: 'Hall',
            email: 'eric.hall@outlook.com',
            phone: '+1-555-012-3450',
            source: 'walk-in',
            subSource: null,
            status: 'new lead',
            stage: 'new',
            budget: '$250k-$500k',
            interestedIn: '3BHK Apartment',
            projectId: null,
            assignedTo: null,
            score: 47,
            tags: JSON.stringify([]),
            notes: null,
            lastContactedAt: null,
            nextCallDate: null,
            createdAt: new Date('2024-12-24').toISOString(),
            updatedAt: new Date('2024-12-24').toISOString(),
        },
        {
            firstName: 'Nisha',
            lastName: 'Chopra',
            email: 'nisha.chopra@gmail.com',
            phone: '+1-555-123-4561',
            source: 'referral',
            subSource: 'Broker Network',
            status: 'booked lead',
            stage: 'attempted 2',
            budget: '$250k-$500k',
            interestedIn: '3BHK Apartment',
            projectId: 9,
            assignedTo: 7,
            score: 77,
            tags: JSON.stringify(['referral-bonus', 'relocating']),
            notes: 'Referred by David Kim. Relocating for job.',
            lastContactedAt: new Date('2024-12-21').toISOString(),
            nextCallDate: new Date('2024-12-28').toISOString(),
            createdAt: new Date('2024-12-04').toISOString(),
            updatedAt: new Date('2024-12-21').toISOString(),
        },
        {
            firstName: 'Tyler',
            lastName: 'Allen',
            email: 'tyler.allen@hotmail.com',
            phone: '+1-555-234-5673',
            source: 'organic',
            subSource: null,
            status: 'new lead',
            stage: 'new',
            budget: '$100k-$250k',
            interestedIn: '2BHK Apartment',
            projectId: null,
            assignedTo: null,
            score: 44,
            tags: JSON.stringify([]),
            notes: null,
            lastContactedAt: null,
            nextCallDate: null,
            createdAt: new Date('2024-12-22').toISOString(),
            updatedAt: new Date('2024-12-22').toISOString(),
        },
        {
            firstName: 'Manisha',
            lastName: 'Agarwal',
            email: 'manisha.agarwal@yahoo.com',
            phone: '+1-555-345-6784',
            source: 'paid',
            subSource: 'Instagram',
            status: 'hot lead',
            stage: 'attempted 1',
            budget: '$1M+',
            interestedIn: 'Penthouse',
            projectId: 12,
            assignedTo: 6,
            score: 93,
            tags: JSON.stringify(['high-value', 'cash-buyer', 'urgent']),
            notes: 'Cash buyer. Looking for luxury unit with terrace.',
            lastContactedAt: new Date('2024-12-24').toISOString(),
            nextCallDate: new Date('2024-12-26').toISOString(),
            createdAt: new Date('2024-12-11').toISOString(),
            updatedAt: new Date('2024-12-24').toISOString(),
        },
        {
            firstName: 'Nathan',
            lastName: 'Young',
            email: 'nathan.young@gmail.com',
            phone: '+1-555-456-7895',
            source: 'organic',
            subSource: null,
            status: 'dead lead',
            stage: 'unqualified',
            budget: '$50k-$100k',
            interestedIn: '1BHK Apartment',
            projectId: null,
            assignedTo: 8,
            score: 24,
            tags: JSON.stringify([]),
            notes: 'Out of budget range.',
            lastContactedAt: new Date('2024-11-18').toISOString(),
            nextCallDate: null,
            createdAt: new Date('2024-10-22').toISOString(),
            updatedAt: new Date('2024-11-18').toISOString(),
        },
        {
            firstName: 'Tanvi',
            lastName: 'Shah',
            email: 'tanvi.shah@outlook.com',
            phone: '+1-555-567-8906',
            source: 'walk-in',
            subSource: null,
            status: 'new lead',
            stage: 'new',
            budget: '$500k-$1M',
            interestedIn: '4BHK Villa',
            projectId: null,
            assignedTo: null,
            score: 65,
            tags: JSON.stringify(['investor']),
            notes: null,
            lastContactedAt: null,
            nextCallDate: null,
            createdAt: new Date('2024-12-23').toISOString(),
            updatedAt: new Date('2024-12-23').toISOString(),
        },
        {
            firstName: 'Aaron',
            lastName: 'King',
            email: 'aaron.king@hotmail.com',
            phone: '+1-555-678-9017',
            source: 'paid',
            subSource: 'Facebook',
            status: 'booked lead',
            stage: 'site visited',
            budget: '$250k-$500k',
            interestedIn: '3BHK Apartment',
            projectId: 14,
            assignedTo: 3,
            score: 81,
            tags: JSON.stringify(['urgent', 'first-time-buyer']),
            notes: 'Visited site last weekend. Very positive.',
            lastContactedAt: new Date('2024-12-23').toISOString(),
            nextCallDate: new Date('2024-12-28').toISOString(),
            createdAt: new Date('2024-12-03').toISOString(),
            updatedAt: new Date('2024-12-23').toISOString(),
        },
        {
            firstName: 'Riya',
            lastName: 'Bansal',
            email: 'riya.bansal@gmail.com',
            phone: '+1-555-789-0128',
            source: 'referral',
            subSource: 'Broker Network',
            status: 'new lead',
            stage: 'attempted 1',
            budget: '$100k-$250k',
            interestedIn: '2BHK Apartment',
            projectId: 6,
            assignedTo: 9,
            score: 58,
            tags: JSON.stringify(['referral-bonus']),
            notes: 'Referred by Emily Rodriguez.',
            lastContactedAt: new Date('2024-12-24').toISOString(),
            nextCallDate: new Date('2024-12-30').toISOString(),
            createdAt: new Date('2024-12-16').toISOString(),
            updatedAt: new Date('2024-12-24').toISOString(),
        },
        {
            firstName: 'Jacob',
            lastName: 'Scott',
            email: 'jacob.scott@yahoo.com',
            phone: '+1-555-890-1239',
            source: 'organic',
            subSource: null,
            status: 'duplicate lead',
            stage: 'new',
            budget: '$250k-$500k',
            interestedIn: '3BHK Apartment',
            projectId: null,
            assignedTo: null,
            score: 8,
            tags: JSON.stringify([]),
            notes: 'Duplicate - already in system.',
            lastContactedAt: null,
            nextCallDate: null,
            createdAt: new Date('2024-12-24').toISOString(),
            updatedAt: new Date('2024-12-24').toISOString(),
        },
        {
            firstName: 'Aditi',
            lastName: 'Pandey',
            email: 'aditi.pandey@outlook.com',
            phone: '+1-555-012-3451',
            source: 'paid',
            subSource: 'Google Ads',
            status: 'hot lead',
            stage: 'attempted 2',
            budget: '$500k-$1M',
            interestedIn: 'Townhouse',
            projectId: 10,
            assignedTo: 2,
            score: 86,
            tags: JSON.stringify(['urgent', 'pre-approved']),
            notes: 'Pre-approved for $600k. Wants corner unit.',
            lastContactedAt: new Date('2024-12-22').toISOString(),
            nextCallDate: new Date('2024-12-27').toISOString(),
            createdAt: new Date('2024-11-24').toISOString(),
            updatedAt: new Date('2024-12-22').toISOString(),
        },
        {
            firstName: 'Zachary',
            lastName: 'Green',
            email: 'zachary.green@gmail.com',
            phone: '+1-555-123-4562',
            source: 'organic',
            subSource: null,
            status: 'new lead',
            stage: 'new',
            budget: '$250k-$500k',
            interestedIn: '3BHK Apartment',
            projectId: null,
            assignedTo: null,
            score: 51,
            tags: JSON.stringify([]),
            notes: null,
            lastContactedAt: null,
            nextCallDate: null,
            createdAt: new Date('2024-12-20').toISOString(),
            updatedAt: new Date('2024-12-20').toISOString(),
        },
        {
            firstName: 'Kritika',
            lastName: 'Mishra',
            email: 'kritika.mishra@hotmail.com',
            phone: '+1-555-234-5674',
            source: 'walk-in',
            subSource: null,
            status: 'new lead',
            stage: 'new',
            budget: '$100k-$250k',
            interestedIn: '2BHK Apartment',
            projectId: null,
            assignedTo: null,
            score: 46,
            tags: JSON.stringify([]),
            notes: null,
            lastContactedAt: null,
            nextCallDate: null,
            createdAt: new Date('2024-12-24').toISOString(),
            updatedAt: new Date('2024-12-24').toISOString(),
        },
        {
            firstName: 'Gregory',
            lastName: 'Baker',
            email: 'gregory.baker@yahoo.com',
            phone: '+1-555-345-6785',
            source: 'paid',
            subSource: 'Instagram',
            status: 'booked lead',
            stage: 'attempted 1',
            budget: '$250k-$500k',
            interestedIn: '3BHK Apartment',
            projectId: 8,
            assignedTo: 5,
            score: 74,
            tags: JSON.stringify(['first-time-buyer', 'relocating']),
            notes: 'Relocating from California. Needs by February.',
            lastContactedAt: new Date('2024-12-23').toISOString(),
            nextCallDate: new Date('2024-12-29').toISOString(),
            createdAt: new Date('2024-12-09').toISOString(),
            updatedAt: new Date('2024-12-23').toISOString(),
        },
        {
            firstName: 'Shruti',
            lastName: 'Bose',
            email: 'shruti.bose@gmail.com',
            phone: '+1-555-456-7896',
            source: 'referral',
            subSource: 'Broker Network',
            status: 'dead lead',
            stage: 'unqualified',
            budget: '$50k-$100k',
            interestedIn: 'Studio Apartment',
            projectId: null,
            assignedTo: 10,
            score: 26,
            tags: JSON.stringify([]),
            notes: 'Looking for rental, not purchase.',
            lastContactedAt: new Date('2024-11-20').toISOString(),
            nextCallDate: null,
            createdAt: new Date('2024-10-30').toISOString(),
            updatedAt: new Date('2024-11-20').toISOString(),
        },
        {
            firstName: 'Samuel',
            lastName: 'Adams',
            email: 'samuel.adams@outlook.com',
            phone: '+1-555-567-8907',
            source: 'organic',
            subSource: null,
            status: 'hot lead',
            stage: 'closed won',
            budget: '$500k-$1M',
            interestedIn: '4BHK Villa',
            projectId: 15,
            assignedTo: 4,
            score: 96,
            tags: JSON.stringify(['cash-buyer']),
            notes: 'Deal closed. Cash payment received.',
            lastContactedAt: new Date('2024-12-19').toISOString(),
            nextCallDate: null,
            createdAt: new Date('2024-10-26').toISOString(),
            updatedAt: new Date('2024-12-19').toISOString(),
        },
        {
            firstName: 'Ishita',
            lastName: 'Sinha',
            email: 'ishita.sinha@hotmail.com',
            phone: '+1-555-678-9018',
            source: 'paid',
            subSource: 'Facebook',
            status: 'new lead',
            stage: 'attempted 2',
            budget: '$250k-$500k',
            interestedIn: '3BHK Apartment',
            projectId: 1,
            assignedTo: 1,
            score: 63,
            tags: JSON.stringify(['first-time-buyer']),
            notes: 'Looking for east-facing units with balcony.',
            lastContactedAt: new Date('2024-12-21').toISOString(),
            nextCallDate: new Date('2024-12-30').toISOString(),
            createdAt: new Date('2024-12-06').toISOString(),
            updatedAt: new Date('2024-12-21').toISOString(),
        },
        {
            firstName: 'Benjamin',
            lastName: 'Nelson',
            email: 'benjamin.nelson@gmail.com',
            phone: '+1-555-789-0129',
            source: 'walk-in',
            subSource: null,
            status: 'new lead',
            stage: 'new',
            budget: '$1M+',
            interestedIn: 'Commercial Space',
            projectId: null,
            assignedTo: null,
            score: 72,
            tags: JSON.stringify(['high-value', 'investor']),
            notes: null,
            lastContactedAt: null,
            nextCallDate: null,
            createdAt: new Date('2024-12-23').toISOString(),
            updatedAt: new Date('2024-12-23').toISOString(),
        },
        {
            firstName: 'Ananya',
            lastName: 'Pillai',
            email: 'ananya.pillai@yahoo.com',
            phone: '+1-555-890-1230',
            source: 'organic',
            subSource: null,
            status: 'hot lead',
            stage: 'site visited',
            budget: '$250k-$500k',
            interestedIn: '3BHK Apartment',
            projectId: 13,
            assignedTo: 7,
            score: 84,
            tags: JSON.stringify(['urgent', 'relocating']),
            notes: 'Visited site twice. Ready to book.',
            lastContactedAt: new Date('2024-12-24').toISOString(),
            nextCallDate: new Date('2024-12-27').toISOString(),
            createdAt: new Date('2024-11-29').toISOString(),
            updatedAt: new Date('2024-12-24').toISOString(),
        },
        {
            firstName: 'Alexander',
            lastName: 'Carter',
            email: 'alexander.carter@outlook.com',
            phone: '+1-555-012-3452',
            source: 'referral',
            subSource: 'Broker Network',
            status: 'booked lead',
            stage: 'attempted 2',
            budget: '$100k-$250k',
            interestedIn: '2BHK Apartment',
            projectId: 4,
            assignedTo: 6,
            score: 79,
            tags: JSON.stringify(['referral-bonus', 'first-time-buyer']),
            notes: 'Referred by Thomas Martinez. Very interested.',
            lastContactedAt: new Date('2024-12-22').toISOString(),
            nextCallDate: new Date('2024-12-28').toISOString(),
            createdAt: new Date('2024-12-05').toISOString(),
            updatedAt: new Date('2024-12-22').toISOString(),
        },
        {
            firstName: 'Preeti',
            lastName: 'Kulkarni',
            email: 'preeti.kulkarni@gmail.com',
            phone: '+1-555-123-4563',
            source: 'paid',
            subSource: 'Google Ads',
            status: 'duplicate lead',
            stage: 'new',
            budget: '$500k-$1M',
            interestedIn: 'Duplex',
            projectId: null,
            assignedTo: null,
            score: 14,
            tags: JSON.stringify([]),
            notes: 'Duplicate - same email as existing lead.',
            lastContactedAt: null,
            nextCallDate: null,
            createdAt: new Date('2024-12-24').toISOString(),
            updatedAt: new Date('2024-12-24').toISOString(),
        },
        {
            firstName: 'Ethan',
            lastName: 'Mitchell',
            email: 'ethan.mitchell@hotmail.com',
            phone: '+1-555-234-5675',
            source: 'organic',
            subSource: null,
            status: 'new lead',
            stage: 'attempted 1',
            budget: '$250k-$500k',
            interestedIn: '3BHK Apartment',
            projectId: 7,
            assignedTo: 8,
            score: 57,
            tags: JSON.stringify([]),
            notes: 'Interested in ground floor units.',
            lastContactedAt: new Date('2024-12-23').toISOString(),
            nextCallDate: new Date('2024-12-31').toISOString(),
            createdAt: new Date('2024-12-17').toISOString(),
            updatedAt: new Date('2024-12-23').toISOString(),
        },
        {
            firstName: 'Simran',
            lastName: 'Ghosh',
            email: 'simran.ghosh@yahoo.com',
            phone: '+1-555-345-6786',
            source: 'paid',
            subSource: 'Instagram',
            status: 'dead lead',
            stage: 'unqualified',
            budget: '$50k-$100k',
            interestedIn: '1BHK Apartment',
            projectId: null,
            assignedTo: 3,
            score: 19,
            tags: JSON.stringify([]),
            notes: 'Not interested in current market.',
            lastContactedAt: new Date('2024-11-14').toISOString(),
            nextCallDate: null,
            createdAt: new Date('2024-10-20').toISOString(),
            updatedAt: new Date('2024-11-14').toISOString(),
        },
        {
            firstName: 'Lucas',
            lastName: 'Perez',
            email: 'lucas.perez@gmail.com',
            phone: '+1-555-456-7897',
            source: 'walk-in',
            subSource: null,
            status: 'new lead',
            stage: 'new',
            budget: '$100k-$250k',
            interestedIn: 'Studio Apartment',
            projectId: null,
            assignedTo: null,
            score: 43,
            tags: JSON.stringify([]),
            notes: null,
            lastContactedAt: null,
            nextCallDate: null,
            createdAt: new Date('2024-12-24').toISOString(),
            updatedAt: new Date('2024-12-24').toISOString(),
        },
        {
            firstName: 'Pallavi',
            lastName: 'Dutta',
            email: 'pallavi.dutta@outlook.com',
            phone: '+1-555-567-8908',
            source: 'referral',
            subSource: 'Broker Network',
            status: 'hot lead',
            stage: 'attempted 1',
            budget: '$500k-$1M',
            interestedIn: '4BHK Apartment',
            projectId: 9,
            assignedTo: 9,
            score: 88,
            tags: JSON.stringify(['urgent', 'pre-approved', 'investor']),
            notes: 'Pre-approved for $750k. Looking for investment property.',
            lastContactedAt: new Date('2024-12-24').toISOString(),
            nextCallDate: new Date('2024-12-27').toISOString(),
            createdAt: new Date('2024-12-18').toISOString(),
            updatedAt: new Date('2024-12-24').toISOString(),
        },
        {
            firstName: 'Mason',
            lastName: 'Roberts',
            email: 'mason.roberts@hotmail.com',
            phone: '+1-555-678-9019',
            source: 'organic',
            subSource: null,
            status: 'booked lead',
            stage: 'site visited',
            budget: '$250k-$500k',
            interestedIn: '3BHK Apartment',
            projectId: 2,
            assignedTo: 10,
            score: 83,
            tags: JSON.stringify(['urgent', 'first-time-buyer']),
            notes: 'Visited site this morning. Very impressed.',
            lastContactedAt: new Date('2024-12-24').toISOString(),
            nextCallDate: new Date('2024-12-28').toISOString(),
            createdAt: new Date('2024-12-01').toISOString(),
            updatedAt: new Date('2024-12-24').toISOString(),
        },
        {
            firstName: 'Tanya',
            lastName: 'Arora',
            email: 'tanya.arora@gmail.com',
            phone: '+1-555-789-0120',
            source: 'paid',
            subSource: 'Facebook',
            status: 'new lead',
            stage: 'new',
            budget: '$100k-$250k',
            interestedIn: '2BHK Apartment',
            projectId: null,
            assignedTo: null,
            score: 49,
            tags: JSON.stringify([]),
            notes: null,
            lastContactedAt: null,
            nextCallDate: null,
            createdAt: new Date('2024-12-19').toISOString(),
            updatedAt: new Date('2024-12-19').toISOString(),
        },
        {
            firstName: 'Logan',
            lastName: 'Turner',
            email: 'logan.turner@yahoo.com',
            phone: '+1-555-890-1231',
            source: 'organic',
            subSource: null,
            status: 'hot lead',
            stage: 'attempted 2',
            budget: '$1M+',
            interestedIn: 'Penthouse',
            projectId: 12,
            assignedTo: 2,
            score: 91,
            tags: JSON.stringify(['high-value', 'cash-buyer', 'urgent']),
            notes: 'Cash buyer. Wants luxury penthouse with pool.',
            lastContactedAt: new Date('2024-12-23').toISOString(),
            nextCallDate: new Date('2024-12-26').toISOString(),
            createdAt: new Date('2024-12-12').toISOString(),
            updatedAt: new Date('2024-12-23').toISOString(),
        },
        {
            firstName: 'Nidhi',
            lastName: 'Chatterjee',
            email: 'nidhi.chatterjee@outlook.com',
            phone: '+1-555-012-3453',
            source: 'walk-in',
            subSource: null,
            status: 'new lead',
            stage: 'new',
            budget: '$250k-$500k',
            interestedIn: '3BHK Apartment',
            projectId: null,
            assignedTo: null,
            score: 53,
            tags: JSON.stringify([]),
            notes: null,
            lastContactedAt: null,
            nextCallDate: null,
            createdAt: new Date('2024-12-23').toISOString(),
            updatedAt: new Date('2024-12-23').toISOString(),
        },
        {
            firstName: 'William',
            lastName: 'Phillips',
            email: 'william.phillips@gmail.com',
            phone: '+1-555-123-4564',
            source: 'paid',
            subSource: 'Google Ads',
            status: 'dead lead',
            stage: 'unqualified',
            budget: '$50k-$100k',
            interestedIn: 'Studio Apartment',
            projectId: null,
            assignedTo: 5,
            score: 21,
            tags: JSON.stringify([]),
            notes: 'Cannot secure financing.',
            lastContactedAt: new Date('2024-11-16').toISOString(),
            nextCallDate: null,
            createdAt: new Date('2024-10-24').toISOString(),
            updatedAt: new Date('2024-11-16').toISOString(),
        },
        {
            firstName: 'Garima',
            lastName: 'Shetty',
            email: 'garima.shetty@hotmail.com',
            phone: '+1-555-234-5676',
            source: 'referral',
            subSource: 'Broker Network',
            status: 'booked lead',
            stage: 'attempted 1',
            budget: '$250k-$500k',
            interestedIn: '3BHK Apartment',
            projectId: 5,
            assignedTo: 4,
            score: 73,
            tags: JSON.stringify(['referral-bonus', 'relocating']),
            notes: 'Referred by Anjali Gupta. Relocating from Texas.',
            lastContactedAt: new Date('2024-12-24').toISOString(),
            nextCallDate: new Date('2024-12-29').toISOString(),
            createdAt: new Date('2024-12-11').toISOString(),
            updatedAt: new Date('2024-12-24').toISOString(),
        },
        {
            firstName: 'Owen',
            lastName: 'Campbell',
            email: 'owen.campbell@yahoo.com',
            phone: '+1-555-345-6787',
            source: 'organic',
            subSource: null,
            status: 'new lead',
            stage: 'attempted 1',
            budget: '$500k-$1M',
            interestedIn: '4BHK Villa',
            projectId: 14,
            assignedTo: 1,
            score: 64,
            tags: JSON.stringify(['investor']),
            notes: 'Looking for villa with large garden space.',
            lastContactedAt: new Date('2024-12-22').toISOString(),
            nextCallDate: new Date('2024-12-30').toISOString(),
            createdAt: new Date('2024-12-14').toISOString(),
            updatedAt: new Date('2024-12-22').toISOString(),
        },
        {
            firstName: 'Vaishali',
            lastName: 'Tiwari',
            email: 'vaishali.tiwari@gmail.com',
            phone: '+1-555-456-7898',
            source: 'paid',
            subSource: 'Instagram',
            status: 'hot lead',
            stage: 'closed won',
            budget: '$100k-$250k',
            interestedIn: '2BHK Apartment',
            projectId: 6,
            assignedTo: 7,
            score: 92,
            tags: JSON.stringify([]),
            notes: 'Deal finalized. Documentation complete.',
            lastContactedAt: new Date('2024-12-21').toISOString(),
            nextCallDate: null,
            createdAt: new Date('2024-10-29').toISOString(),
            updatedAt: new Date('2024-12-21').toISOString(),
        },
        {
            firstName: 'Dylan',
            lastName: 'Parker',
            email: 'dylan.parker@outlook.com',
            phone: '+1-555-567-8909',
            source: 'walk-in',
            subSource: null,
            status: 'duplicate lead',
            stage: 'new',
            budget: '$250k-$500k',
            interestedIn: '3BHK Apartment',
            projectId: null,
            assignedTo: null,
            score: 11,
            tags: JSON.stringify([]),
            notes: 'Duplicate - merge with lead #5678.',
            lastContactedAt: null,
            nextCallDate: null,
            createdAt: new Date('2024-12-24').toISOString(),
            updatedAt: new Date('2024-12-24').toISOString(),
        },
        {
            firstName: 'Megha',
            lastName: 'Kapur',
            email: 'megha.kapur@hotmail.com',
            phone: '+1-555-678-9010',
            source: 'organic',
            subSource: null,
            status: 'new lead',
            stage: 'attempted 2',
            budget: '$250k-$500k',
            interestedIn: '3BHK Apartment',
            projectId: 11,
            assignedTo: 6,
            score: 61,
            tags: JSON.stringify(['first-time-buyer']),
            notes: 'Looking for west-facing units with good ventilation.',
            lastContactedAt: new Date('2024-12-20').toISOString(),
            nextCallDate: new Date('2024-12-31').toISOString(),
            createdAt: new Date('2024-12-07').toISOString(),
            updatedAt: new Date('2024-12-20').toISOString(),
        },
        {
            firstName: 'Isaac',
            lastName: 'Evans',
            email: 'isaac.evans@gmail.com',
            phone: '+1-555-789-0121',
            source: 'paid',
            subSource: 'Facebook',
            status: 'dead lead',
            stage: 'unqualified',
            budget: '$50k-$100k',
            interestedIn: '1BHK Apartment',
            projectId: null,
            assignedTo: 8,
            score: 23,
            tags: JSON.stringify([]),
            notes: 'Plans changed - moving to different city.',
            lastContactedAt: new Date('2024-11-22').toISOString(),
            nextCallDate: null,
            createdAt: new Date('2024-10-28').toISOString(),
            updatedAt: new Date('2024-11-22').toISOString(),
        },
        {
            firstName: 'Shweta',
            lastName: 'Bajaj',
            email: 'shweta.bajaj@yahoo.com',
            phone: '+1-555-890-1232',
            source: 'referral',
            subSource: 'Broker Network',
            status: 'hot lead',
            stage: 'site visited',
            budget: '$500k-$1M',
            interestedIn: 'Townhouse',
            projectId: 10,
            assignedTo: 3,
            score: 87,
            tags: JSON.stringify(['urgent', 'pre-approved']),
            notes: 'Pre-approved for $800k. Visited site yesterday.',
            lastContactedAt: new Date('2024-12-23').toISOString(),
            nextCallDate: new Date('2024-12-27').toISOString(),
            createdAt: new Date('2024-11-26').toISOString(),
            updatedAt: new Date('2024-12-23').toISOString(),
        },
        {
            firstName: 'Christian',
            lastName: 'Edwards',
            email: 'christian.edwards@outlook.com',
            phone: '+1-555-012-3454',
            source: 'organic',
            subSource: null,
            status: 'new lead',
            stage: 'new',
            budget: '$100k-$250k',
            interestedIn: '2BHK Apartment',
            projectId: null,
            assignedTo: null,
            score: 41,
            tags: JSON.stringify([]),
            notes: null,
            lastContactedAt: null,
            nextCallDate: null,
            createdAt: new Date('2024-12-21').toISOString(),
            updatedAt: new Date('2024-12-21').toISOString(),
        },
        {
            firstName: 'Khushi',
            lastName: 'Jain',
            email: 'khushi.jain@gmail.com',
            phone: '+1-555-123-4565',
            source: 'paid',
            subSource: 'Google Ads',
            status: 'booked lead',
            stage: 'attempted 2',
            budget: '$250k-$500k',
            interestedIn: '3BHK Apartment',
            projectId: 3,
            assignedTo: 9,
            score: 78,
            tags: JSON.stringify(['urgent', 'first-time-buyer']),
            notes: 'Ready to book. Waiting for loan approval.',
            lastContactedAt: new Date('2024-12-21').toISOString(),
            nextCallDate: new Date('2024-12-28').toISOString(),
            createdAt: new Date('2024-12-03').toISOString(),
            updatedAt: new Date('2024-12-21').toISOString(),
        },
        {
            firstName: 'Hunter',
            lastName: 'Collins',
            email: 'hunter.collins@hotmail.com',
            phone: '+1-555-234-5677',
            source: 'walk-in',
            subSource: null,
            status: 'new lead',
            stage: 'new',
            budget: '$1M+',
            interestedIn: 'Office Space',
            projectId: null,
            assignedTo: null,
            score: 69,
            tags: JSON.stringify(['high-value', 'investor']),
            notes: null,
            lastContactedAt: null,
            nextCallDate: null,
            createdAt: new Date('2024-12-23').toISOString(),
            updatedAt: new Date('2024-12-23').toISOString(),
        },
        {
            firstName: 'Ritika',
            lastName: 'Soni',
            email: 'ritika.soni@yahoo.com',
            phone: '+1-555-345-6788',
            source: 'organic',
            subSource: null,
            status: 'hot lead',
            stage: 'attempted 1',
            budget: '$250k-$500k',
            interestedIn: '3BHK Apartment',
            projectId: 15,
            assignedTo: 10,
            score: 86,
            tags: JSON.stringify(['urgent', 'relocating']),
            notes: 'Relocating for new job. Needs by end of January.',
            lastContactedAt: new Date('2024-12-24').toISOString(),
            nextCallDate: new Date('2024-12-26').toISOString(),
            createdAt: new Date('2024-12-15').toISOString(),
            updatedAt: new Date('2024-12-24').toISOString(),
        },
        {
            firstName: 'Gavin',
            lastName: 'Stewart',
            email: 'gavin.stewart@gmail.com',
            phone: '+1-555-456-7899',
            source: 'paid',
            subSource: 'Instagram',
            status: 'dead lead',
            stage: 'unqualified',
            budget: '$50k-$100k',
            interestedIn: 'Studio Apartment',
            projectId: null,
            assignedTo: 2,
            score: 27,
            tags: JSON.stringify([]),
            notes: 'Lost job - cannot proceed.',
            lastContactedAt: new Date('2024-11-25').toISOString(),
            nextCallDate: null,
            createdAt: new Date('2024-11-01').toISOString(),
            updatedAt: new Date('2024-11-25').toISOString(),
        },
        {
            firstName: 'Payal',
            lastName: 'Mathur',
            email: 'payal.mathur@outlook.com',
            phone: '+1-555-567-8900',
            source: 'referral',
            subSource: 'Broker Network',
            status: 'new lead',
            stage: 'attempted 1',
            budget: '$500k-$1M',
            interestedIn: 'Duplex',
            projectId: 11,
            assignedTo: 5,
            score: 66,
            tags: JSON.stringify(['referral-bonus', 'investor']),
            notes: 'Referred by Swati Malhotra. Investment property.',
            lastContactedAt: new Date('2024-12-24').toISOString(),
            nextCallDate: new Date('2024-12-30').toISOString(),
            createdAt: new Date('2024-12-19').toISOString(),
            updatedAt: new Date('2024-12-24').toISOString(),
        },
        {
            firstName: 'Austin',
            lastName: 'Morris',
            email: 'austin.morris@hotmail.com',
            phone: '+1-555-678-9011',
            source: 'organic',
            subSource: null,
            status: 'booked lead',
            stage: 'site visited',
            budget: '$250k-$500k',
            interestedIn: '3BHK Apartment',
            projectId: 1,
            assignedTo: 4,
            score: 82,
            tags: JSON.stringify(['urgent', 'first-time-buyer']),
            notes: 'Site visit scheduled for this weekend.',
            lastContactedAt: new Date('2024-12-24').toISOString(),
            nextCallDate: new Date('2024-12-27').toISOString(),
            createdAt: new Date('2024-12-02').toISOString(),
            updatedAt: new Date('2024-12-24').toISOString(),
        },
        {
            firstName: 'Anjana',
            lastName: 'Bhardwaj',
            email: 'anjana.bhardwaj@gmail.com',
            phone: '+1-555-789-0122',
            source: 'paid',
            subSource: 'Facebook',
            status: 'new lead',
            stage: 'new',
            budget: '$100k-$250k',
            interestedIn: '2BHK Apartment',
            projectId: null,
            assignedTo: null,
            score: 48,
            tags: JSON.stringify([]),
            notes: null,
            lastContactedAt: null,
            nextCallDate: null,
            createdAt: new Date('2024-12-18').toISOString(),
            updatedAt: new Date('2024-12-18').toISOString(),
        },
        {
            firstName: 'Colton',
            lastName: 'Rogers',
            email: 'colton.rogers@yahoo.com',
            phone: '+1-555-890-1233',
            source: 'walk-in',
            subSource: null,
            status: 'duplicate lead',
            stage: 'new',
            budget: '$250k-$500k',
            interestedIn: '3BHK Apartment',
            projectId: null,
            assignedTo: null,
            score: 9,
            tags: JSON.stringify([]),
            notes: 'Duplicate - same phone as existing lead.',
            lastContactedAt: null,
            nextCallDate: null,
            createdAt: new Date('2024-12-24').toISOString(),
            updatedAt: new Date('2024-12-24').toISOString(),
        },
        {
            firstName: 'Shreya',
            lastName: 'Chauhan',
            email: 'shreya.chauhan@outlook.com',
            phone: '+1-555-012-3455',
            source: 'organic',
            subSource: null,
            status: 'hot lead',
            stage: 'attempted 2',
            budget: '$500k-$1M',
            interestedIn: '4BHK Villa',
            projectId: 7,
            assignedTo: 1,
            score: 89,
            tags: JSON.stringify(['urgent', 'pre-approved', 'cash-buyer']),
            notes: 'Pre-approved for $900k. Can close quickly.',
            lastContactedAt: new Date('2024-12-23').toISOString(),
            nextCallDate: new Date('2024-12-26').toISOString(),
            createdAt: new Date('2024-11-21').toISOString(),
            updatedAt: new Date('2024-12-23').toISOString(),
        },
        {
            firstName: 'Landon',
            lastName: 'Reed',
            email: 'landon.reed@gmail.com',
            phone: '+1-555-123-4566',
            source: 'paid',
            subSource: 'Google Ads',
            status: 'new lead',
            stage: 'attempted 1',
            budget: '$250k-$500k',
            interestedIn: '3BHK Apartment',
            projectId: 8,
            assignedTo: 7,
            score: 59,
            tags: JSON.stringify(['first-time-buyer']),
            notes: 'Interested in units with modular kitchen.',
            lastContactedAt: new Date('2024-12-23').toISOString(),
            nextCallDate: new Date('2024-12-31').toISOString(),
            createdAt: new Date('2024-12-16').toISOString(),
            updatedAt: new Date('2024-12-23').toISOString(),
        },
        {
            firstName: 'Diya',
            lastName: 'Bhatt',
            email: 'diya.bhatt@hotmail.com',
            phone: '+1-555-234-5678',
            source: 'referral',
            subSource: 'Broker Network',
            status: 'dead lead',
            stage: 'unqualified',
            budget: '$50k-$100k',
            interestedIn: '1BHK Apartment',
            projectId: null,
            assignedTo: 6,
            score: 29,
            tags: JSON.stringify([]),
            notes: 'Decided to continue renting.',
            lastContactedAt: new Date('2024-11-28').toISOString(),
            nextCallDate: null,
            createdAt: new Date('2024-11-05').toISOString(),
            updatedAt: new Date('2024-11-28').toISOString(),
        },
        {
            firstName: 'Wyatt',
            lastName: 'Cook',
            email: 'wyatt.cook@yahoo.com',
            phone: '+1-555-345-6789',
            source: 'organic',
            subSource: null,
            status: 'booked lead',
            stage: 'attempted 1',
            budget: '$100k-$250k',
            interestedIn: '2BHK Apartment',
            projectId: 4,
            assignedTo: 8,
            score: 71,
            tags: JSON.stringify(['first-time-buyer', 'relocating']),
            notes: 'Relocating from Miami. Needs parking space.',
            lastContactedAt: new Date('2024-12-24').toISOString(),
            nextCallDate: new Date('2024-12-28').toISOString(),
            createdAt: new Date('2024-12-08').toISOString(),
            updatedAt: new Date('2024-12-24').toISOString(),
        },
        {
            firstName: 'Aishwarya',
            lastName: 'Saxena',
            email: 'aishwarya.saxena@gmail.com',
            phone: '+1-555-456-7890',
            source: 'paid',
            subSource: 'Instagram',
            status: 'hot lead',
            stage: 'site visited',
            budget: '$250k-$500k',
            interestedIn: '3BHK Apartment',
            projectId: 12,
            assignedTo: 3,
            score: 85,
            tags: JSON.stringify(['urgent', 'relocating']),
            notes: 'Visited site last week. Ready to proceed.',
            lastContactedAt: new Date('2024-12-24').toISOString(),
            nextCallDate: new Date('2024-12-27').toISOString(),
            createdAt: new Date('2024-12-04').toISOString(),
            updatedAt: new Date('2024-12-24').toISOString(),
        },
        {
            firstName: 'Levi',
            lastName: 'Morgan',
            email: 'levi.morgan@outlook.com',
            phone: '+1-555-567-8901',
            source: 'walk-in',
            subSource: null,
            status: 'new lead',
            stage: 'new',
            budget: '$1M+',
            interestedIn: 'Retail Space',
            projectId: null,
            assignedTo: null,
            score: 67,
            tags: JSON.stringify(['high-value', 'investor']),
            notes: null,
            lastContactedAt: null,
            nextCallDate: null,
            createdAt: new Date('2024-12-22').toISOString(),
            updatedAt: new Date('2024-12-22').toISOString(),
        },
        {
            firstName: 'Jhanvi',
            lastName: 'Sinha',
            email: 'jhanvi.sinha@hotmail.com',
            phone: '+1-555-678-9012',
            source: 'organic',
            subSource: null,
            status: 'new lead',
            stage: 'attempted 2',
            budget: '$250k-$500k',
            interestedIn: '3BHK Apartment',
            projectId: 13,
            assignedTo: 9,
            score: 62,
            tags: JSON.stringify([]),
            notes: 'Looking for units near schools.',
            lastContactedAt: new Date('2024-12-19').toISOString(),
            nextCallDate: new Date('2024-12-30').toISOString(),
            createdAt: new Date('2024-12-06').toISOString(),
            updatedAt: new Date('2024-12-19').toISOString(),
        },
        {
            firstName: 'Connor',
            lastName: 'Bell',
            email: 'connor.bell@gmail.com',
            phone: '+1-555-789-0123',
            source: 'paid',
            subSource: 'Facebook',
            status: 'hot lead',
            stage: 'closed won',
            budget: '$500k-$1M',
            interestedIn: 'Townhouse',
            projectId: 14,
            assignedTo: 10,
            score: 97,
            tags: JSON.stringify(['cash-buyer']),
            notes: 'Deal closed successfully. Full payment received.',
            lastContactedAt: new Date('2024-12-17').toISOString(),
            nextCallDate: null,
            createdAt: new Date('2024-10-23').toISOString(),
            updatedAt: new Date('2024-12-17').toISOString(),
        },
        {
            firstName: 'Priyanka',
            lastName: 'Rathore',
            email: 'priyanka.rathore@yahoo.com',
            phone: '+1-555-890-1234',
            source: 'referral',
            subSource: 'Broker Network',
            status: 'booked lead',
            stage: 'attempted 2',
            budget: '$250k-$500k',
            interestedIn: '3BHK Apartment',
            projectId: 5,
            assignedTo: 2,
            score: 80,
            tags: JSON.stringify(['referral-bonus', 'urgent']),
            notes: 'Referred by Logan Turner. Very motivated buyer.',
            lastContactedAt: new Date('2024-12-20').toISOString(),
            nextCallDate: new Date('2024-12-27').toISOString(),
            createdAt: new Date('2024-12-01').toISOString(),
            updatedAt: new Date('2024-12-20').toISOString(),
        },
        {
            firstName: 'Jeremiah',
            lastName: 'Murphy',
            email: 'jeremiah.murphy@outlook.com',
            phone: '+1-555-012-3456',
            source: 'organic',
            subSource: null,
            status: 'duplicate lead',
            stage: 'new',
            budget: '$100k-$250k',
            interestedIn: '2BHK Apartment',
            projectId: null,
            assignedTo: null,
            score: 13,
            tags: JSON.stringify([]),
            notes: 'Duplicate - already contacted.',
            lastContactedAt: null,
            nextCallDate: null,
            createdAt: new Date('2024-12-24').toISOString(),
            updatedAt: new Date('2024-12-24').toISOString(),
        },
        {
            firstName: 'Kavita',
            lastName: 'Pandya',
            email: 'kavita.pandya@gmail.com',
            phone: '+1-555-123-4567',
            source: 'paid',
            subSource: 'Google Ads',
            status: 'new lead',
            stage: 'new',
            budget: '$250k-$500k',
            interestedIn: '3BHK Apartment',
            projectId: null,
            assignedTo: null,
            score: 52,
            tags: JSON.stringify([]),
            notes: null,
            lastContactedAt: null,
            nextCallDate: null,
            createdAt: new Date('2024-12-20').toISOString(),
            updatedAt: new Date('2024-12-20').toISOString(),
        },
    ];

    await db.insert(leads).values(sampleLeads);
    
    console.log('✅ Leads seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});